#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CircleImageView.Resource.Attribute.border_color = global::Sample.Resource.Attribute.border_color;
			global::CircleImageView.Resource.Attribute.border_width = global::Sample.Resource.Attribute.border_width;
			global::CircleImageView.Resource.Styleable.CircleImageView = global::Sample.Resource.Styleable.CircleImageView;
			global::CircleImageView.Resource.Styleable.CircleImageView_border_color = global::Sample.Resource.Styleable.CircleImageView_border_color;
			global::CircleImageView.Resource.Styleable.CircleImageView_border_width = global::Sample.Resource.Styleable.CircleImageView_border_width;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int border_color = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int border_width = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bob = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CircleImageView_border_color = 1;
			
			// aapt resource value: 0
			public const int CircleImageView_border_width = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
